FROM node:10.16.2-alpine AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine

EXPOSE 80
ENV VUE_APP_TODO_API http://localhost:5001/api
COPY --from=build /app/docs /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]