apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: eloyvegabootcamp/bootcamp-webinar-frontend
        ports:
        - containerPort: 3000
        env:
        - name: VUE_APP_TODO_API
          value: "http://a1b754040d4db11e984930acb8470106-643682577.us-east-1.elb.amazonaws.com/api"
          
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000